//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Globalization;

namespace NuPattern.Properties
{
	///	<summary>
	///	Provides access to string resources.
	///	</summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("netfx-System.Strings", "1.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	static partial class Strings
	{
		///	<summary>
		///	Provides access to string resources.
		///	</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("netfx-System.Strings", "1.0.0.0")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public static partial class Collection
		{
			/// <summary>
			/// Looks up a localized string similar to: 
			///	An item with the same name '{name}' already exists.
			/// </summary>
			public static string DuplicateItemName(object name)
			{
				return Resources.Collection_DuplicateItemName.FormatWith(new 
				{
					name = name,
				});
			}
		}
		
		///	<summary>
		///	Provides access to string resources.
		///	</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("netfx-System.Strings", "1.0.0.0")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public static partial class Component
		{
			/// <summary>
			/// Looks up a localized string similar to: 
			///	A property with the same name '{name}' already exists.
			/// </summary>
			public static string DuplicatePropertyName(object name)
			{
				return Resources.Component_DuplicatePropertyName.FormatWith(new 
				{
					name = name,
				});
			}
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Cannot create property named 'Name' since it is a reserved property that always exists for components.
			/// </summary>
			public static string NamePropertyReserved { get { return Resources.Component_NamePropertyReserved; } }
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Component '{name}' has existing schema '{existingSchemaId}' which does not match the specified schema value with id '{newSchemaId}'.
			/// </summary>
			public static string SchemaMismatch(object name, object existingSchemaId, object newSchemaId)
			{
				return Resources.Component_SchemaMismatch.FormatWith(new 
				{
					name = name,
					existingSchemaId = existingSchemaId,
					newSchemaId = newSchemaId,
				});
			}
		}
		
		///	<summary>
		///	Provides access to string resources.
		///	</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("netfx-System.Strings", "1.0.0.0")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public static partial class Container
		{
			/// <summary>
			/// Looks up a localized string similar to: 
			///	A component with the same name '{name}' already exists.
			/// </summary>
			public static string DuplicateComponentName(object name)
			{
				return Resources.Container_DuplicateComponentName.FormatWith(new 
				{
					name = name,
				});
			}
		}
		
		///	<summary>
		///	Provides access to string resources.
		///	</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("netfx-System.Strings", "1.0.0.0")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public static partial class JsonProductSerializer
		{
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Invalid document. Expected '$format' property with a valid version string (i.e. '2.0').
			/// </summary>
			public static string InvalidFormat { get { return Resources.JsonProductSerializer_InvalidFormat; } }
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Invalid document. Expected '$items' object property to contain collection elements.
			/// </summary>
			public static string InvalidItems { get { return Resources.JsonProductSerializer_InvalidItems; } }
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Invalid document. Expected '$format' property with the document version.
			/// </summary>
			public static string MissingFormat { get { return Resources.JsonProductSerializer_MissingFormat; } }
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Invalid document. Expected '$schema' property with component schema definition identifier.
			/// </summary>
			public static string MissingSchema { get { return Resources.JsonProductSerializer_MissingSchema; } }
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Invalid document. Expected '$toolkit' property with the owning toolkit information.
			/// </summary>
			public static string MissingToolkit { get { return Resources.JsonProductSerializer_MissingToolkit; } }
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Invalid document. Expected '$id' property with the owning toolkit identifier.
			/// </summary>
			public static string MissingToolkitId { get { return Resources.JsonProductSerializer_MissingToolkitId; } }
		
			/// <summary>
			/// Looks up a localized string similar to: 
			///	Invalid document. Expected '$version' property with the owning toolkit version.
			/// </summary>
			public static string MissingToolkitVersion { get { return Resources.JsonProductSerializer_MissingToolkitVersion; } }
		}
	}
}

