//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuPattern.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuPattern.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item with the same name &apos;{name}&apos; already exists..
        /// </summary>
        internal static string Collection_DuplicateItemName {
            get {
                return ResourceManager.GetString("Collection_DuplicateItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A property with the same name &apos;{name}&apos; already exists..
        /// </summary>
        internal static string Component_DuplicatePropertyName {
            get {
                return ResourceManager.GetString("Component_DuplicatePropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create property named &apos;Name&apos; since it is a reserved property that always exists for components..
        /// </summary>
        internal static string Component_NamePropertyReserved {
            get {
                return ResourceManager.GetString("Component_NamePropertyReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component &apos;{name}&apos; has existing schema &apos;{existingSchemaId}&apos; which does not match the specified schema value with id &apos;{newSchemaId}&apos;..
        /// </summary>
        internal static string Component_SchemaMismatch {
            get {
                return ResourceManager.GetString("Component_SchemaMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A property with the same name &apos;{name}&apos; already exists..
        /// </summary>
        internal static string ComponentSchema_DuplicatePropertyName {
            get {
                return ResourceManager.GetString("ComponentSchema_DuplicatePropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create property named &apos;Name&apos; since it is a reserved property that always exists for components..
        /// </summary>
        internal static string ComponentSchema_NamePropertyReserved {
            get {
                return ResourceManager.GetString("ComponentSchema_NamePropertyReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create component because a property named &apos;{propertyName}&apos; already exists on &apos;{containerName}&apos;..
        /// </summary>
        internal static string Container_ComponentNameMatchesProperty {
            get {
                return ResourceManager.GetString("Container_ComponentNameMatchesProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A component with the same name &apos;{name}&apos; already exists..
        /// </summary>
        internal static string Container_DuplicateComponentName {
            get {
                return ResourceManager.GetString("Container_DuplicateComponentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot rename component &apos;{oldName}&apos; to &apos;{newName}&apos; because its parent &apos;{container}&apos; already has a component with the same name..
        /// </summary>
        internal static string Container_RenamedDuplicateComponent {
            get {
                return ResourceManager.GetString("Container_RenamedDuplicateComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot rename component &apos;{oldName}&apos; to &apos;{newName}&apos; because its parent &apos;{container}&apos; already has a property with the same name..
        /// </summary>
        internal static string Container_RenamedDuplicateProperty {
            get {
                return ResourceManager.GetString("Container_RenamedDuplicateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid document. Expected &apos;$format&apos; property with a valid version string (i.e. &apos;2.0&apos;)..
        /// </summary>
        internal static string JsonProductSerializer_InvalidFormat {
            get {
                return ResourceManager.GetString("JsonProductSerializer_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid document. Expected &apos;$items&apos; object property to contain collection elements..
        /// </summary>
        internal static string JsonProductSerializer_InvalidItems {
            get {
                return ResourceManager.GetString("JsonProductSerializer_InvalidItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid document. Expected &apos;$format&apos; property with the document version..
        /// </summary>
        internal static string JsonProductSerializer_MissingFormat {
            get {
                return ResourceManager.GetString("JsonProductSerializer_MissingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid document. Expected &apos;$schema&apos; property with component schema definition identifier..
        /// </summary>
        internal static string JsonProductSerializer_MissingSchema {
            get {
                return ResourceManager.GetString("JsonProductSerializer_MissingSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid document. Expected &apos;$toolkit&apos; property with the owning toolkit information..
        /// </summary>
        internal static string JsonProductSerializer_MissingToolkit {
            get {
                return ResourceManager.GetString("JsonProductSerializer_MissingToolkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid document. Expected &apos;$id&apos; property with the owning toolkit identifier..
        /// </summary>
        internal static string JsonProductSerializer_MissingToolkitId {
            get {
                return ResourceManager.GetString("JsonProductSerializer_MissingToolkitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid document. Expected &apos;$version&apos; property with the owning toolkit version..
        /// </summary>
        internal static string JsonProductSerializer_MissingToolkitVersion {
            get {
                return ResourceManager.GetString("JsonProductSerializer_MissingToolkitVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A product with the same name &apos;{name}&apos; already exists in the store &apos;{store}&apos;..
        /// </summary>
        internal static string ProductStore_DuplicateProductName {
            get {
                return ResourceManager.GetString("ProductStore_DuplicateProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot rename product &apos;{oldName}&apos; to &apos;{newName}&apos; because the store &apos;{store}&apos; already has a product with the same name..
        /// </summary>
        internal static string ProductStore_RenamedDuplicateProduct {
            get {
                return ResourceManager.GetString("ProductStore_RenamedDuplicateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product model can only contain interfaces and primitive types. Invalid type &apos;{type}&apos;..
        /// </summary>
        internal static string SchemaBuilder_ModelMustBeInterfaces {
            get {
                return ResourceManager.GetString("SchemaBuilder_ModelMustBeInterfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved property &apos;Name&apos; must be of type string..
        /// </summary>
        internal static string SchemaBuilder_NamePropertyMustBeString {
            get {
                return ResourceManager.GetString("SchemaBuilder_NamePropertyMustBeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified instance is not a product interface..
        /// </summary>
        internal static string SmartCast_InstanceNotProductInterface {
            get {
                return ResourceManager.GetString("SmartCast_InstanceNotProductInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart casting only works with interfaces..
        /// </summary>
        internal static string SmartCast_InterfaceRequired {
            get {
                return ResourceManager.GetString("SmartCast_InterfaceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only property get/set calls can be performed on a product interface..
        /// </summary>
        internal static string SmartCast_NotPropertyAccess {
            get {
                return ResourceManager.GetString("SmartCast_NotPropertyAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart casting requires the given component &apos;{component}&apos; to have an associated schema..
        /// </summary>
        internal static string SmartCast_SchemaRequired {
            get {
                return ResourceManager.GetString("SmartCast_SchemaRequired", resourceCulture);
            }
        }
    }
}
